### ISSUE TITLE
Support for other assets (WP Super Cache etc)

### ISSUE THREAD

**Issue by drewsymo** [deliciousbrains/wp-amazon-s3-and-cloudfront#144]
Is it possible to allow support for uploading cache files to S3 / CloudFront? e.g. the cache folder that is created by WP Super Cache?

**Comment by tomasdev** [comment]
:+1: Yes. Absolutely. Those static HTML served might be faster? I'm not 100% sure that a network request would win over a local SSD file request.

But might be worthy investigating.

Just think even with tens of thousands of htmls, the filesize of all those is quite trivial (specially gzipped) against image sizing.

**Comment by bradt** [comment]
Why use WP Super Cache + CloudFront? Why not just use CloudFront to cache and serve your content?

**Comment by A5hleyRich** [comment]
Not a planned feature.

It doesn't make sense to serve cached pages from CloudFront as the original request still needs to hit the server to then forward it to CloudFront. It would be quicker to just serve the static version from your local server.

**Comment by leoloso** [comment]
Hi @bradt @A5hleyRich 

I wonder if you would reconsidering not adding this feature, at least for uploading to S3 the folder created by WP Super Cache with all cached files. That's because there's an issue right now: by saving the cached files locally, these files are out of sync among instances. Eg: I have set to delete the cache whenever a new post is published, but it deletes the cache only from that one instance, so my cached homepage from all other instances will not show the new post.

Thanks

**Comment by A5hleyRich** [comment]
This is still not something we plan on implementing. @leoloso can you not use a shared filesystem across those instances, or use some custom logic to clear the cache?

**Comment by leoloso** [comment]
Hi @A5hleyRich 

Implementing some logic to keep the cache in sync may be tricky, since each instance is not aware of all other instances. WP Super Cache allows to clear the cache a new post is published, but this instance can't instruct all other instances to clear their cache too. Adding some extra logic, eg: check if there was a new post at the beginning of each request and if so clear the cache, is inefficient.

I'm not using a shared filesystem for the cache, each instance keeps the cache locally, so they are constantly out of sync. I think to put them in S3 would be best, because it's also efficient: if an instance has already cached a page, then all instances can use it, and no cached page will be stale.

If I'm not wrong, W3 Total Cache allows its cache to be placed in S3, but I don't use that plugin because it's not maintained anymore (it was last updated more than 9 months ago), so some users are migrating to other plugins, such as WP Super Cache. 

So if in the future you would consider adding this feature, it would be awesome.

Thanks!
