### ISSUE TITLE
Changing path in the plugin settings affects only newly added media

### ISSUE THREAD

**Issue by wujekbogdan** [deliciousbrains/wp-amazon-s3-and-cloudfront#301]
Trying to solve this issue https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/300 I started to play with various plugin settings. First of all, I've changed the custom path to default (`wp-content/uploads`). All newly added images have a proper path, but old media files (added before I've changed this setting) still has the old one. It happens in the WP admin and on the front-end.

It looks like there's something wrong with URL rewriting. 

I wonder is it a bug, maybe it's intentional?

**Comment by A5hleyRich** [comment]
That's the expected behaviour. URLs aren't rewritten, which is why they don't update to reflect the new settings. For this to work we would have to perform a find and replace on the database when settings have changed, which isn't something we plan on implementing.

We are looking into alternative solutions though.
