### ISSUE TITLE
error fetching buckets

### ISSUE THREAD

**Issue by frankscalzo** [deliciousbrains/wp-amazon-s3-and-cloudfront#322]
I get this error fetching buckets 

Error fetching buckets — SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

when i try to create a bucket i error as well

[vroom.avalere.com-diagnostic-log-20160527104857.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/286297/vroom.avalere.com-diagnostic-log-20160527104857.txt)

**Comment by polevaultweb** [comment]
@frankscalzo  can you try editing your wp-config.php file to replace this line - 

  define( 'WP_DEBUG', false );

With these lines - 

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false); 

This means that any errors are logged to `/wp-content/debug.log`, because some errors are not visible on screen. 

Can you try the process again and then send on the `debug.log` file if created please.

**Comment by frankscalzo** [comment]
Error fetching buckets — SyntaxError: Unexpected token \ in JSON at position 0

Here is the only line in debug

[27-May-2016 10:54:49 UTC] Sorry, but recursing filters on "the_content" breaks NextGEN Gallery. Please see https://core.trac.wordpress.org/ticket/17817 and NGG_DISABLE_FILTER_THE_CONTENT

**Comment by frankscalzo** [comment]
Fixed the issue there was a / in my header.php before the main code breaking everything

**Comment by polevaultweb** [comment]
@frankscalzo great!
