### ISSUE TITLE
Plugin doesn't seem to work with "Featured Images"

### ISSUE THREAD

**Issue by tonyd256** [deliciousbrains/wp-amazon-s3-and-cloudfront#341]
I'm trying to set this plugin up for a wordpress site that uses a theme that supports featured images. When I create a new post I can attached a "Featured Image" to it. The plugin captures the upload event correctly and uploads the file to S3 correctly and everything works great. However, when viewing a published page, these featured images don't appear. Their `img` tags have empty `src` attributes. Any ideas what would cause this?

**Comment by ianmjones** [comment]
What code does the theme use to display the featured image?

**Comment by tonyd256** [comment]
@ianmjones Looks like it uses Aqua Resizer. Did some research and it looks like others have had this issue in the past. Has a workaround been established?

**Comment by ianmjones** [comment]
As Aqua Resizer dynamically resizes and crops without using the standard WordPress functions to register and save its image sizes, there's not much we can do at the moment. However
 we will keep looking for ways to work with dynamic croppers.

The best solution at the moment is to use separate media library items specifically for use by Aqua Resizer, leaving them on the local server rather than uploading to S3.
