### ISSUE TITLE
Rewrite URL doesn't force old links to new cloudfront URLs

### ISSUE THREAD

**Issue by Serpentsoft** [deliciousbrains/wp-amazon-s3-and-cloudfront#373]
Hi Pal,

The plugin doesn't force old media files to read links from S3 and Cloudfront, I should use CDN Enabler plugin to force old URLs,

I have WP_DEBUG and WP_DEBUG_LOG but no issue appears.

WordPress v.4.7.4

Thanks.

**Comment by ianmjones** [comment]
@Serpentsoft please can you post your diagnostic info from the Help tab, and also an example of the URL that should be filtered but wasn't, and what you expected it to be filtered to?

**Comment by Serpentsoft** [comment]
Can you provide any private chat to send you these data?? is that ok to send an email to ian@ianmjones.com?

**Comment by ianmjones** [comment]
@Serpentsoft Removed my email from your comment so I hopefully get less spam.

Please send diagnostic info and a clarification of the issue to nom at our domain and I'll take a look.

**Comment by Serpentsoft** [comment]
Thanks Pal,

Sent to nom [at] ian.....com

**Comment by ianmjones** [comment]
The problem turned out to be that @Serpentsoft expected images manually uploaded to S3 to be linked up to Media Library items automatically, WP Offload S3 currently can't do that and needs to upload Media Library items to S3 itself in order to save metadata about where on S3 each Media Library item is.
