### ISSUE TITLE
This item has not been copied to S3 yet.

### ISSUE THREAD

**Issue by websirs** [deliciousbrains/wp-amazon-s3-and-cloudfront#397]
Hi,

Thank you for this awesome plugin.

Uploading new media will be sent to S3 and served through CloudFront with no problems.

The issue is all previously uploaded files are still being loaded from WordPress website and when accessing the media via WordPress it says "This item has not been copied to S3"

I have used the Amazon command line tool to upload all media files on S3.

How can we set the plugin to serve from CloudFront URL?

Thank you

**Comment by aaemnnosttv** [comment]
Thank you websirs!

Unfortunately, Offload S3 is not currently compatible with files uploaded to S3 outside of WordPress (e.g. awscli). The plugin needs to save S3 data for each file when it is uploaded to be able to rewrite URLs correctly. This is why the plugin shows the file has not been uploaded to S3 yet, because the plugin did not upload it, so it has no knowledge of the objects you uploaded.

For sites with existing media libraries, we recommend upgrading to the pro version of [Offload S3](https://deliciousbrains.com/wp-offload-s3/), which allows you to upload any media library items to S3 which have not uploaded yet, among many other features.
