### ISSUE TITLE
Interoperability with WP Retina 2x plugin

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-s3-and-cloudfront#4]
Continuing the conversation from http://wordpress.org/support/topic/retina-2x-amazon-s3?replies=7.

Jordy, maybe you can help save me some time with answers to the following:
1. When uploading a new media item, what is the best way to get the file paths of the generated @2x images?
2. When removing a media item, what would be the best way to get a list of the @2x files for that media item? Are you storing this info in the post meta?

Thanks,
Brad

**Comment by travelmassive** [comment]
Hi all I am going to Lazarus this issue because it's worthy of some additional comments.

I have purchased both WP Offload S3 and WP Retina 2x Pro.

As a customer, it's a bit disappointing that even after so many years these two great plugin fail to integrate :(

I'm certain we're only a few lines of code away from this working. What can be done to resolve this? 

I see that @jordymeow offered up a function 'wr2x_retina_file_added' which is still in his code base. What we need is some advice or sample code from @bradt for how to hook this in to WP Offload S3 so that the retina images get moved over to S3 after they are generated.

I also tried the (since removed from WP Offload S3) code suggested in this gist but it doesn't work -> https://gist.github.com/polevaultweb/d5e2af9150e0495d078b

I am certain I'm not the only person looking for a solution here. Thanks!

**Comment by jordymeow** [comment]
I am not sure I should ask this question, but why aren't you using a conventional CDN? It works, it integrates with all kinds of plugins, it doesn't require uploads, can refresh, reset cache when images are updated/replaced, and also cache all your static content (not only images). I use S3 for non-WordPress related projects, and I like it, but for WordPress projects, I would definitely not use it.

For your issue, it would work with Retina and the PictureFill method, you would need to check the http check but that's all. Of course, S3 would need to upload the retina photos as well.

**Comment by travelmassive** [comment]
Thanks for quick reply - re: CDN. Why do I use S3 + Cloudfront? Well... I manage a multi-platform site (Drupal for our community platform, Wordpress for our blog, Discourse for our community forums) and so there is an overhead of complexity that I face as a developer and admin - multiple codebases, multiple servers, multiple databases, multiple backups, development environments, SSO, keeping everything up to date, paying licensing and server bills, the list goes on. Plus supporting our 38,000+ members. Therefore sticking to S3 + Cloudfront helps keep things sane from an ops POV.

Thinking about the solution here... perhaps a middleware plugin that can act on your wr2x_retina_file_added method to upload the file(s) to S3 so we are sure that there will be a @2x version available. Are the retina image urls kept in the database so they can be modified, or does your plugin scan the file system directly to determine what retina images can be used?

**Comment by jordymeow** [comment]
Exactly, you could do that. Just upload the file manually (or by modifying the S3 plugin) through the wr2x_retina_file_added filter. It's there for that reason basically. Then my plugin scans the system OR performs a http request (check the retina settings) to find the retina file, and include it in the srcset.

**Comment by ianmjones** [comment]
I just had a play with the two plugins, trying to get things working with a slightly altered version of our Tweaks plugin example of adding extra files for upload using our [`as3cf_attachment_file_paths`](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/3e83234e96f67b823ae94d27385cf9603d149c0b/amazon-s3-and-cloudfront-tweaks.php#L262) filter, it didn't go so well.

The `@2x` images could be uploaded to S3 OK, but not with the bulk uploader for some reason. If you use "Remove Files From Server" then things go wonky as those extra files are not removed from local.

The biggest problem is that the 'srcset' always loses the `@2x` files even though they have been uploaded to S3 due to them not being part of the registered image sizes. Maybe WP Retina 2x's CDN option can fix that, I don't know, but it skips changing the URLs that WP Offload S3 swaps in for registered image sizes (WP Retina 2x has a much later priority on the relevant filter). I tried all the methods for swapping in the 2x files, no dice.

If WP Retina 2x augmented the registered image sizes and hid its new ones from user selection then I guess WP Offload S3 would just use them without issue, but as it stands there are too many gotchas for us to be able to support it.

The function I link to above used to use an `apply_file_suffix` function that no longer exists, it's been replaced in that Tweaks example with a simple concatenation of pathinfo parts. That's why @polevaultweb's [gist](https://gist.github.com/polevaultweb/d5e2af9150e0495d078b) no longer works too, it uses the old `apply_file_suffix` function.

If anyone were to come up with a cast-iron set of filters/functions that could be added to the Tweaks plugin to restore compatibility between the two plugins, we'd definitely review the PR.

**Comment by travelmassive** [comment]
Hi all

Thanks for your comments and feedback which set me in the right direction.

After some research, I came up with this solution:

`// upload retina images to s3
add_action( 'wr2x_retina_file_added', 'tm_wr2x_retina_file_added', 10, 2 );
function tm_wr2x_retina_file_added( $attachment_id, $retina_filepath ) {

        if (function_exists('as3cf_init') or (function_exists( 'as3cf_pro_init'))) {

                global $as3cf;

                $post_id = null;
                $metadata = null;
                $file_path = $retina_filepath;
                $force_new_s3_client = false;
                $remove_local_files = false;

                $s3_data = $as3cf->upload_attachment_to_s3($attachment_id, $metadata, $file_path, $force_new_s3_client, $remove_local_files);

                return ! is_wp_error( $s3_data );
        }

        return false;
}
`

Hope this helps others. I'm using this in production and it's working for me - but it there might be side-effects so as always this suggestion is without warranty.

**Comment by jordymeow** [comment]
@travelmassive Thanks a lot for this code. That seems very easy :) I am interested in sharing this code on my FAQ, is that ok? I have also another plugin for synchronizing Lightroom with WordPress and a code in "those lines" might be nice to have, but in my case, I would need to replace already uploaded images.

**Comment by travelmassive** [comment]
@jordymeow - yes, of course feel free to share - glad I could be of some assistance.
