### ISSUE TITLE
Object Versioning

### ISSUE THREAD

**Issue by xcrap** [deliciousbrains/wp-amazon-s3-and-cloudfront#405]
I'm trying to move the files out of S3 again to Media Library, but all my upload folders have Object Versioning so they don't end normally at 

/uploads/year/month/file 

but instead...

/uploads/year/month/cache/file

The problem is if I move everything to media library and disable the plugins they will not match because of that cache folder. I have a couple of hundred folders already and it will be weeks to manually remove them. Is there a way to remove all cache folders from S3 somehow ?

* Also keep in mind that I didn't had the files in Media Library, the only place they exist was at the bucket, I had to download all of them from S3 Bucket to the Media Library.

**Comment by xcrap** [comment]
> WP Offload S3
> 
> Before deactivating and deleting the plugin you must ensure all Media Library files exist locally. To do so, visit the WP Offload S3 settings screen and click the ‘Begin Download’ button (Pro only). This will download all Media Library files from S3 to your local server.

Well I believe I'm searching for something like this, it's not available at WP Offload S3 Lite ? Because to buy the full version only to download the media...

**Comment by ianmjones** [comment]
Unfortunately we currently don't have another solution for you other than our WP Offload S3 plugin.

WP Offload S3 Lite has Object Versioning enabled by default as it's important when using CloudFront or another CDN to be able to "bust the cache" if something like Enabled Media Replace is used to replace an image. Accordingly WP Offload S3 Lite does not enable the Remove Files From Server option by default as it makes it harder to just turn off WP Offload S3 Lite and start using the local Media Library again. WP Offload S3 Lite warns about turning on Remove Files From Server because some plugins expect there to be a local file, we'll look into warning about having both Object Versioning and Remove Files From Server turned on at the same time too.

If you don't want to use WP Offload S3's "Remove Files From S3" or "Download Files From S3" tools, remember that WP Offload S3 Lite stores information about where each Media Library item's files are on S3 in `postmeta` records with a `meta_key` of 'amazonS3_info'.

**Comment by xcrap** [comment]
Well, you should really have this warning there when the Object Versioning is enabled.

Because users like me for example, that  are transition for Google Cloud and have some projects that I can't afford the full script (and it's a very good plugin), if we want to move out it would be a problem.

Now instead of using the "amazonS3_info" for making some sort of script that would rename and remove the files, I will try flatten a nested directory, the problem is that I will have to repeat this procedure for every month in the last 4 years where the folders exists. Maybe this is useful information for someone who needs. After that I'll upload all the files again to the /uploads/ folder and disable the scripts to have the Media Library working normally again

http://osxdaily.com/2015/02/11/flatten-nested-directory-structure-command-line/

But thanks a lot for the information.
Take care.
