### ISSUE TITLE
S3 Image URL Replacement fails with multiple Polylang domains

### ISSUE THREAD

**Issue by sulfo** [deliciousbrains/wp-amazon-s3-and-cloudfront#411]
We have a website with 4 languages and the plugin works great on our main site (Let's call it domain.dk)

When we upload or choose a image from the other sites (domain.se, domain.no) it fails replacing the local URL to S3.

It's due to this method:
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/761e98dad46938e58cf36a85fb536f146a7fe9ea/classes/filters/as3cf-local-to-s3.php#L115-L127

This method is returning false on domain.se, domain.no, and true on domain.dk.

`$uploads['baseurl']` always return the main sites URL (domain.dk).

I know you don't have Polylang support so I'm unsure if you qualify this as a bug. However I would like to ask if there's any known solution (like a filter to pass in custom domain?).

#370 might be related to this.

**Comment by ianmjones** [comment]
Because WP Offload S3 uses `wp_upload_dir()` to get the `baseurl` for comparison with the currently processing URL, you could probably change the `baseurl` in the `upload_dir` filter that `wp_upload_dir()` calls before returning its results array. You'd need to be careful to only change that based on the current page's language etc.

There are a couple of potential features and integrations that would benefit from WP Offload S3 being able to match on multiple domains, so we're definitely looking into adding that sometime in the future and such a feature would likely have a filter exposed.

**Comment by sulfo** [comment]
Thanks for the reply.

We fixed it for now by using the `upload_dir` filter as you suggested.
Here's the code for others having the same issue.

```
if(!is_admin()) {
    add_filter('upload_dir', function($cacheKey){
        $cacheKey['baseurl'] = pll_home_url(PLL()->options['default_lang']) . 'app/uploads';
        return $cacheKey;
    });
}
```

Thanks for your help!
