### ISSUE TITLE
Re-writing back to the local url 

### ISSUE THREAD

**Issue by lb-emma** [deliciousbrains/wp-amazon-s3-and-cloudfront#412]
When adding amazon s3 links in the editor they are being re-written on our website to the local url, and cannot be forced back to s3 link. 

This is what it looks like in our editor, the links stay as the s3 links here after publishing
<img width="1680" alt="screen shot 2017-11-08 at 16 21 04" src="https://user-images.githubusercontent.com/33492581/32560711-44a75096-c4a2-11e7-9f6f-d414cdc9120a.png">

However, within the live website view the src is still the local url not the s3 link
<img width="1680" alt="screen shot 2017-11-08 at 16 20 57" src="https://user-images.githubusercontent.com/33492581/32560715-483cee0a-c4a2-11e7-8fb5-717d1b57e749.png">

Are we missing an option somewhere/is there a way for it not to rewrite to the local url?

**Comment by A5hleyRich** [comment]
URL rewriting is performed on `the_content` filter. Is that filter applied to the page output? This docs article explains it in more detail:

https://deliciousbrains.com/wp-offload-s3/doc/filtering-urls-in-custom-content/

**Comment by axertion** [comment]
I have the same issue here.  The problem can be replicated if you have a Wordpress site that is hosted locally (local dev server), and on a public production server.

For example, let's say you have this scenario:

*Production:* https://mysite.com/
*Local Dev:* https://mysite.localhost.com/

If you upload / embed an image on mysite.com, the img url embedded is this:

`https://mysite.com/wp-content/uploads/2017/05/photo.jpg`

which gets converted into:

`https://d17ads3ax9je3vm.cloudfront.net/2017/05/103045631/photo.jpg`

However, if you switch to edit the same post on `https://mysite.localhost.com/`, the image URL *is not converted* leaving it to appear as the original filename:

`https://mysite.com/wp-content/uploads/2017/05/photo.jpg`

And when you try to preview the post on `https://mysite.localhost.com/`, the image doesn't load because it's not using the S3 image url, it's using the `mysite.com` url (and the image doesn't exist!)

---
**Possible Solution:**
There needs to be a way to define an alternate URL (other than the base_url) that the plugin will find/replace with the S3 url.

For example, I could input `https://mysite.localhost.com/`, and the plugin would find/replace both `base_url` and the `dev_url`.

**Comment by axertion** [comment]
As a hack, I've updated the `url_needs_replacing` function in 2 plugin files to also check for the localhost url in addition to the base url.

**wp-content/plugins/amazon-s3-and-cloudfront/classes/filters/as3cf-local-to-s3.php**

	protected function url_needs_replacing( $url ) {
		$uploads  = wp_upload_dir();
		$base_url = $this->as3cf->maybe_fix_local_subsite_url( $uploads['baseurl'] );
		$base_url = AS3CF_Utils::remove_scheme( $base_url );

		if ( false !== strpos( $url, $base_url ) ) {
			// Local URL, perform replacement
			return true;
		}

		//Hack fix for localhost
		$dev_url = 'http://mysite.localhost.com/wp-content/uploads'; //replace with your localhost dev server
		$dev_url = AS3CF_Utils::remove_scheme( $dev_url );
		if ( false !== strpos( $url, $dev_url ) ) {
			// Local URL, perform replacement
			return true;
		}

		// Remote URL, no replacement needed
		return false;
	}

**wp-content/plugins/amazon-s3-and-cloudfront/classes/filters/as3cf-s3-to-local.php**

	protected function url_needs_replacing( $url ) {
		$uploads  = wp_upload_dir();
		$base_url = AS3CF_Utils::remove_scheme( $uploads['baseurl'] );

		if ( false !== strpos( $url, $base_url ) ) {
			// Local URL, no replacement needed
			return false;
		}

		//Hack fix for localhost
		$dev_url = 'http://mysite.localhost.com/wp-content/uploads'; //replace with your localhost dev server
		$base_url = AS3CF_Utils::remove_scheme( $dev_url );
		if ( false !== strpos( $url, $base_url ) ) {
			// Local URL, perform replacement
			return false;
		}

		// Remote URL, perform replacement
		return true;
	}

**Comment by ianmjones** [comment]
@axertion We strongly recommend not updating the source files for WP Offload S3 Lite like this, you will lose your changes every time the plugin is updated.

A better interim solution would be to add a custom implementation of the `upload_dir` filter that recognises that the current domain is different to the configured domain and updates the returned `baseurl` with the current domain.

However, we've had a few people request support for filtering multiple domains on the same site, we're definitely looking to support it in a future version.

**Comment by axertion** [comment]
@ianmjones - Thanks for the tip, I did just that.

I basically added this to my theme's functions.php as temporary fix until the plugin has the functionality for multiple domain filtering.

```
function fix_amazon_s3_upload_dir( $param ){
    $current_site_url = get_site_url();
    $localhost_url = "http://mysite.localhost.com";
    $production_url = "https://mysite.com";

    if($current_site_url == $localhost_url) {
      $param['baseurl'] = str_replace($localhost_url, $production_url, $param['baseurl']);
    }

    return $param;
}
add_filter('upload_dir', 'fix_amazon_s3_upload_dir');

```

**Comment by ianmjones** [comment]
This issue seems to have diverted from the original request which was more of a support request to the problem of having multiple domains applicable to the same site/data which is covered by issue #363.
