### ISSUE TITLE
Issue with get_the_post_thumbnail_url

### ISSUE THREAD

**Issue by edubuc** [deliciousbrains/wp-amazon-s3-and-cloudfront#434]
Hi,
If you go on https://patisserie-oueslati.com/produit/adlia-pistache-pignon-noisette/ the thumbnail image for the product appears broken.

It seems that:
> get_the_post_thumbnail_url( $post->ID, 'woocommerce_thumbnail' )

Returns s3euwest2://... in the "<div data-thumb" tag (instead of https://s3-eu-west-2...)

It happened when I upgraded to the latest WooCommerce version. Do you have an idea of why it happens?

**Comment by ianmjones** [comment]
Unfortunately this is a problem with the latest version of WooCommerce, they are [aware of the issue](https://wordpress.org/support/topic/version-3-3-1-upgrade-php-warnings-on-product-page/) and are [working on a fix](https://github.com/woocommerce/woocommerce/pull/18850).

Until the fix is released we can only advise keeping your images local as well as on S3 so that WooCommerce's on-the-fly thumbnail generation does not cause problems.
