### ISSUE TITLE
Offload S3 and WPML issue

### ISSUE THREAD

**Issue by khalidahmada** [deliciousbrains/wp-amazon-s3-and-cloudfront#450]
Hi,

I activate plugin Offload S3, and everything work just fine. But I have an issue with WPML When I switch to secondary language (Fr) the link to my CloudFront missed out and show the classic links to my website media WP.

Please help.

**Comment by ianmjones** [comment]
WP Offload S3 has a built in [integration for WPML](https://deliciousbrains.com/wp-offload-s3/doc/wpml-integration/).

Otherwise, please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
