### ISSUE TITLE
Incompatibility with WPML

### ISSUE THREAD

**Issue by GlueDigiStu** [deliciousbrains/wp-amazon-s3-and-cloudfront#465]
I have an issue where translated images aren't using the S3 offload URL. I reported it to WPML and they say the issue is incompatibility due to the Offload S3 plugin and not their plugin. 
https://wpml.org/forums/topic/offload-s3-integration-not-working/page/3/

I've had a look at the files they specify, and can't really see their issue but they've asked me to log this so here I am!!

**Comment by Bazze** [comment]
> [...] We know WP Offload S3 is compatible with WPML v4.0.3+, but have not verified whether WP Offload S3 Lite is too.

Fair enough, but is it your intention to verify that it is? And if not, work on a fix for it? 😃

**Comment by ianmjones** [comment]
As WPML is a premium 3rd party plugin we can only spend resources on testing and supporting it for our own premium plugin.

However, we'll likely check compatibility with Lite during our next major release's testing phase, it would be nice if it supported the current release of WPML too. If any problems arise and it's a super simple fix we'd likely do it if it also means a simpler Pro plugin too.

WPML is a moving target though, and there's lots of "if" and "maybe" above, so while support for WPML would be nice in Lite, we can only commit to supporting it with Pro.

**Comment by ianmjones** [comment]
Turns out WPML still enables their duplicating of Media Library items by default within the core plugin, regardless of whether you're using the better translation addons.

As such, WP Offload Media 2.3 has improved WPML integration that better handles some edge cases related to manipulating the individual language duplicates, e.g. protecting against removing from bucket via one language, while duplicates in other languages still need the objects.

WP Offload Media Lite 2.3 gains some protections in this area too, but for complete WPML support you will need WP Offload Media.
