### ISSUE TITLE
Multiple Simultaneous Buckets

### ISSUE THREAD

**Issue by clarter** [deliciousbrains/wp-amazon-s3-and-cloudfront#476]
Has there ever been any discussion around allowing for two or more buckets to offload to in the case of another S3 outage? From my perspective I could see writing to any number of buckets and then on our end we would use our CDN to hit a Route53 address that would balance the GETs.

**Comment by ianmjones** [comment]
Hi @clarter,

Yes, definitely been proposed by customers before.

The thing is, if WP Offload Media was to write to two or more buckets on each offload, it would potentially double the time taken to do so purely because of the doubling of network traffic, risking a timeout, or requiring backgrounding of the task.

With the current synchronous offload when adding new media to the media library it's definitely a no-go, but we do have plans to potentially offload in the background, which might make such a feature feasible. It would require being able to configure multiple providers and buckets, and storing information about the multiple remote versions for each media library item. That's a massive change to WP Offload Media.

However, I expect there are ways to do this kind of thing already with lambda functions or similar copying objects from one provider to another. I know Google Cloud Storage has the ability to suck in an S3 bucket, but I'm not sure if it could do a conditional copy in of missing items etc.

On switchover to the backup storage provider you'd need to update WP Offload Media's config and then update every Media Library item's 'amazonS3_info' record to use the new provider's details.

A simpler solution is to not remove the local media and just turn off WP Offload Media's "Rewrite Media URLs" setting until AWS is back! But admittedly, some sites simply can't store all the media locally.

**Comment by clarter** [comment]
Thanks, I appreciate the detailed response. We do currently employ S3 replication to another region which is an option built in to AWS S3. The concern I'm trying to overcome is what happens if there is another extended S3 outage in a single region. This is definitely not something I expect this plugin to solve, was just checking on alternatives.

Currently in our setup, when an image is uploaded, it is stored in the usual uploads directory which is mounted to an EFS volume and shared among all web servers in a single region. We use the plugin to store the images in S3 for backup purposes, but we're considering making S3 the default serving location if we can find a better way of making it redundant in multiple regions.

Thanks again!
