### ISSUE TITLE
Compatibility with Polylang Pro

### ISSUE THREAD

**Issue by Chouby** [deliciousbrains/wp-amazon-s3-and-cloudfront#491]
I am a developper of Polylang and Polylang Pro. One of our customers reported an issue that you can see in this video made by the customer: https://drive.google.com/file/d/10Dfrv2uG2ssODbuR8lmMrYIVd6RgnYxF/view?usp=sharing

As I understand, your plugin is modifying the attachment url. When creating a new media translation, we duplicate the source media to the new language with this method: https://github.com/polylang/polylang/blob/2.5.2/include/crud-posts.php#L244-L293
As you can see, the meta `_wp_attached_file` is copied from the source to the translation.

In the video, we see that the url is correctly modified when the translation is manually created (click on the + icon in the metabox). In this case `create_media_translation` is hooked to `admin_init`. 

However Polylang Pro offers an option to automatically create the translations at upload (the option is active in the video). The video shows that in this case the link in the translation is incorrect, although we use the same method to create the translation, but this time hooked to `add_attachment` (we hook to the original media insertion to create all the translations).

How your plugin does know which url to use? What step could be missing when creating the media translation by hooking to `add_attachment` instead of `admin_init`?

**Comment by ianmjones** [comment]
It basically boils down to new uploads to the Media Library are usually offloaded by WP Offload Media when the `wp_update_attachment_metadata` filter is fired. e.g. when something like the following occurs...

`wp_update_attachment_metadata( $attachment->ID, wp_generate_attachment_metadata( $attachment->ID, $file ) );`

WP Offload Media then offloads the file(s) and creates its `amazonS3_info` postmeta record for the new attachment. That record has the data that tells WP Offload Media the Media Library item has been offloaded, where it is, and therefore it can filter local URLs in content to the remote version.

I've no idea why there's a difference between the two methods you're using for creating the duplicates.

However, I do know that the way you're duplicating Media Library items without duplicating the files (e.g. using the same path on disk via the `_wp_attached_file` record) is not how WordPress expects the Media Library to handle files, and could cause a World of hurt.

I was surprised to see that in the video, after the ML item was successfully duplicated is gained the exact same object versioned URL as the original. Would be interesting to see whether that's because the `amazonS3_info` record was duplicated, or whether Pollylang is filtering the attachment ID if the media file hasn't been altered from the original?

**Comment by ianmjones** [comment]
It basically boils down to new uploads to the Media Library are usually offloaded by WP Offload Media when the `wp_update_attachment_metadata` filter is fired. e.g. when something like the following occurs...

`wp_update_attachment_metadata( $attachment->ID, wp_generate_attachment_metadata( $attachment->ID, $file ) );`

WP Offload Media then offloads the file(s) and creates its `amazonS3_info` postmeta record for the new attachment. That record has the data that tells WP Offload Media the Media Library item has been offloaded, where it is, and therefore it can filter local URLs in content to the remote version.

I've no idea why there's a difference between the two methods you're using for creating the duplicates.

However, I do know that the way you're duplicating Media Library items without duplicating the files (e.g. using the same path on disk via the `_wp_attached_file` record) is not how WordPress expects the Media Library to handle files, and could cause a World of hurt.

I was surprised to see that in the video, after the ML item was successfully duplicated is gained the exact same object versioned URL as the original. Would be interesting to see whether that's because the `amazonS3_info` record was duplicated, or whether Pollylang is filtering the attachment ID if the media file hasn't been altered from the original?

**Comment by Chouby** [comment]
Thank you for your answer. 

I proposed this code snippet to our caustomer:
```php
add_action( 'pll_translate_media', function( $post_id, $tr_id ) {
	wp_update_attachment_metadata( $tr_id, wp_get_attachment_metadata( $tr_id ) );
}, 10, 2 ); 
```
to make sure that the `wp_update_attachment_metadata` filter is passed for all created attachments. But the result was the opposite as what we are looking for. 

Further investigating, it looks like, without the code above, the url is correct for the duplicated attachments (those created by Polylang Pro) and is incorrect for the original attachment. 

Have you an idea of what could prevent your plugin to modify the url?

**Comment by ianmjones** [comment]
> Have you an idea of what could prevent your plugin to modify the url?

Can you check that the original ML item has an "amazonS3_info" postmeta record?

**Comment by ianmjones** [comment]
I've had some great information from a customer that confirmed what's going on with Polylang.

Two scenarios:

1) Media Library item already offloaded, Polylang then creates a translation of the ML item.

2) Polylang creates translation of local only Media Library item, WP Offload Media later offloads all media (this is with Pro).

It basically sounds like Polylang copies all the postmeta data associated with a Media Library item when it creates a translation, this postmeta data includes WP Offload Media's "amazonS3_info" records in scenario (1). That is why translating an already offloaded Media Library item references the same path in the bucket.

In the opposite scenario (2), when an already translated Media Library item is offloaded, each duplicate Media Library item is treated as a separate ML item to be offloaded by WP Offload Media because WP Offload Media does not know about the relationship between the items.

This is totally expected behaviour for WP Offload Media, as each WordPress Media Library item should be discrete and have a unique local file path.

Unfortunately, plugins like Polylang and WPML break the convention and use the same local path for multiple Media Library items.

WP Offload Media (Pro) has an integration for WPML that combats this problem, but WP Offload Media does not have an integration for Polylang.

Recent versions of WPML include an alternate method of translation that allows re-use of the same Media Library item across all translated content, with just the captions etc. being translated. If an image needs translation because it includes text or locale specific data that should be changed for the different languages, then a new Media Library item is added with a **new image** that works as WordPress and WP Offload Media would expect, and is linked to the original purely through metadata and not paths etc.

It would be awesome if Polylang could adopt a similar mechanism, and even better if it could cleanly upgrade translated media from the old method to the new method, something WPML has failed to do and therefore means WP Offload Media needs to keep its WPML integration for the time being.

It would of course be awesome if WP Offload Media could "just recognise duplicate Media Library items and not re-offload them and protect bucket objects from deletion when being used by multiple ML items", but the WordPress database is simply not storing the metadata in a way that would allow for these checks without crippling the server for larger Media Libraries.

**Comment by Chouby** [comment]
Sorry for the late answer. I could test this only today. The meta "amazonS3_info" was indeed missing for the attachments causing the issue. Synchronizing it accross media translations solves our customer issue and now all translations use the correct media on S3. Thanks for pointing me to this meta.

It's possible however that there is an upload request for each media translation as WP Offload Media is indeed not aware of the relationship between translations. I did not check.

In my tests with WPML, I still see one attachment per language with all of them having the same meta values. That's the case for example for `_wp_attached_file`. However I did not test WPML and WP Offload Media together.

**Comment by ianmjones** [comment]
> In my tests with WPML, I still see one attachment per language in the database with all of them having the same meta values. That's the case for example for `_wp_attached_file`.

Yup, WPML still has the "duplicate media" setting turned on by default, which causes this behaviour, even when the Translation Management addons are installed and active. It's a pain.

Longing for the day when WPML properly deprecates and then removes the duplicate media functionality. Not that I've heard this is the plan, sadly. 😢

**Comment by Chouby** [comment]
Thanks to the contribution of Daniel Berkman, we will add some compatibility with WP Offload Media in Polylang 2.6: https://github.com/polylang/polylang/commit/ccca192b856359cfb2f4b3b01fd692adeeadaeaa

The class synchronizes the `amazonS3_info` and `as3cf_filesize_total` metas across media translations. It also prevents WP Offload Media to delete media files if they are in use by another media translation by deleting these 2 metas before WP Offload Media acts.

Thank you for your valuable information.

**Comment by ianmjones** [comment]
@Chouby That's awesome, please let us know when it's released and we'll add Polylang to our list of [Plugins That Integrate With WP Offload Media](https://deliciousbrains.com/wp-offload-media/doc/compatibility-with-other-plugins/#plugins-that-integrate).

**Comment by ianmjones** [comment]
@Chouby saw the Tweet, so have added Polylang to our Compatibility With Other Plugins doc. 🎉
