### ISSUE TITLE
Do not require public access to S3 bucket

### ISSUE THREAD

**Issue by Ayodehi** [deliciousbrains/wp-amazon-s3-and-cloudfront#492]
When using Amazon Cloudfront CDN, there is no reason to require objects be made public in the S3 bucket. Please consider supporting an option to not set public.

For security reasons, I have blocked public access at the account level. Without it, I cannot justify purchase, despite the otherwise high quality work.

For anyone who is experiencing access denied in their properly secured architecture, the solution temporarily is just one line change:

/classes/providers/aws-provider.php

from:
147 `const DEFAULT_ACL = 'public-read';`

to: 
147 `const DEFAULT_ACL = 'private';`

**Comment by ianmjones** [comment]
By default a new bucket does not have public access to add/update/delete/search/index the objects, which is great and works well with WP Offload Media.

However, if you want site visitors to see your offloaded images then individual objects need to have a public **read** ACL.

If you want all offloads to have a private ACL, and therefore need signed URLs for access, then you can use the `as3cf_upload_acl` filter to change the ACL to be used for each offload.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/cb7c645d84969d58b43dd43b918c6c5c75218099/amazon-s3-and-cloudfront-tweaks.php#L327

At the moment, if you do use signed URLs for offloads then you will not be able to use a custom domain/CDN for delivering those images etc. unless you're using GCS.

Please do *not* change the `DEFAULT_ACL` constant! Apart from the fact that you will loose your changes on every update to WP Offload Media, you are likely breaking all kinds of things in WP Offload Media!

**Comment by Ayodehi** [comment]
I appreciate the hint about `as3cf_upload_acl`.

_However, if you want site visitors to see your offloaded images then individual objects need to have a public read ACL._

_If you want all offloads to have a private ACL, and therefore need signed URLs for access,_

This was true in the past but is no longer the case. When using Cloudfront, you do not need signed URLs and you do not need public access to objects in your bucket. You may now use what's called an "Origin Access Identity" which will grant Cloudfront access to your bucket while keeping everything private. As such, if there was an easy configuration option to choose between granting public access and keeping objects private, this plugin would be very easy to use in both insecure and secured environments.

Here is how I'm currently using the plugin in a secured environment with no public access at all:

EC2 IAM Policy:

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::bucketname/*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::bucketname"
        }
    ]
}```

Cloudfront Origin Settings:

Restrict Bucket Access: Yes
Origin Access Identity: (Create new, or use existing -- this is a special user identity that will give Cloudfront rights to your private bucket)
Grant Read Permissions on Bucket: Yes

**Comment by ianmjones** [comment]
Ah, ok, that's a very different thing, I was mislead by your reference to the ACL stuff.

Yep, it would be nice if WP Offload Media could support buckets with no public access with CloudFront as only avenue for public access.

**Comment by schoenkaft** [comment]
We're currently facing the same issue. 

Our S3 bucket is set to private and only CloudFront is granted access. Writing to the S3 bucket with `public-read` results in an error, which is what we want. Public access is delivered through CloudFront pointing to the S3 website endpoint.

Setting the ACL to `private` via the `as3cf_upload_acl` kind of works, but this assumes that we'd want S3 Pre-Signed URLs (as discussed in https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/427). However, that's not the behaviour we're looking for, and even feels like a false assumption. It might make more sense to move that assumption to a more configurable option?

Changing the ACL via the `as3cf_upload_acl` hook also doesn't seem to pass the `can_write` check, since that's using the hardcoded `self::DEFAULT_ACL` which is set to `public-read`. So setting it to anything other than `public-read` or `private` (like `aws-exec-read`) will still show the warning when viewing the plugin and its settings. Even though it 'works'. 

In the end, we just want to set it to `private`. Would be awesome if this (expected) behaviour could be supported!

**Comment by mcolomboid** [comment]
same here

**Comment by mcroiban** [comment]
I am having the same issue. Are there any updates as to when this feature will be implemented?

**Comment by ggedde** [comment]
Same Here

**Comment by noonii** [comment]
+1

**Comment by iconictb** [comment]
+1

**Comment by ianmjones** [comment]
WP Offload Media (Lite) 2.4 now has support for **Block All Public Access to Bucket**. 🎉 

https://deliciousbrains.com/wp-offload-media/doc/block-all-public-access-to-bucket/
