### ISSUE TITLE
media_handle_sideload not working

### ISSUE THREAD

**Issue by desmeit** [deliciousbrains/wp-amazon-s3-and-cloudfront#497]
According to this post it should be possible to upload with 

`media_handle_sideload`

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/354

I tried it with that code:

```

require_once(ABSPATH . '/wp-admin/includes/file.php');
require_once(ABSPATH . '/wp-admin/includes/media.php');
require_once(ABSPATH . '/wp-admin/includes/image.php');

$user = get_user_by('email', 'XXX');

$foto1 = $user->foto1;
$url = content_url() . $foto1;

$temp_file = download_url( $url );


	$file = array(
		'name'     => basename($url),
		'type'     => 'image/png',
		'tmp_name' => $temp_file,
		'error'    => 0,
		'size'     => filesize($temp_file),
	);

$id = media_handle_sideload( $file, 0, basename($url) );
```

The upload to the media library is working but the upload to S3 doesn't work. It seems that W3 Offload does not register the function.

What can I do?

**Comment by desmeit** [comment]
I tried a lot.

Also `wp_handle_sideload` with this example:

https://codex.wordpress.org/Function_Reference/wp_handle_sideload

is not working. I did some tests and I think the filter 

`wp_update_attachment_metadata`

is not calling. `wp_handle_upload` is working properly.

**Comment by desmeit** [comment]
Too bad that nobody from the developers is answering.

I solved it now but its only working with ajax.

**Comment by ianmjones** [comment]
WP Offload Media's offloading for new media library items is usually triggered by the `wp_update_attachment_metadata` filter.

At the end of `media_handle_sideload` you'll see the following code...

```
	// Save the attachment metadata
	$id = wp_insert_attachment( $attachment, $file, $post_id, true );
	if ( ! is_wp_error( $id ) ) {
		wp_update_attachment_metadata( $id, wp_generate_attachment_metadata( $id, $file ) );
	}
```

You should chuck some debug in there to make sure that `wp_update_attachment_metadata` happens.

Otherwise, please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

**Comment by desmeit** [comment]
The solution is:

Use `wp_loaded` instead of `init`. 

https://codex.wordpress.org/Plugin_API/Action_Reference/init
> Fires after WordPress has finished loading but before any headers are sent.

https://codex.wordpress.org/Plugin_API/Action_Reference/wp_loaded
> If you wish to plug an action once WP is loaded, use the wp_loaded hook.
