### ISSUE TITLE
Transfer between buckets

### ISSUE THREAD

**Issue by tiagoboeing** [deliciousbrains/wp-amazon-s3-and-cloudfront#504]
I have a bucket with contents of media library and the upload was via plugin. I needed create a new bucket in another account and transfer the content. I had migrate the bucket contents for the current account to another in AWS and create a new range. (I migrate all content with AWS CLI)

When editing a property `"bucket";s:16:"mybucket-aws..."` of records with `meta_key = 'amazonS3_info'` in the `wp_postmeta` table, the content lost reference for bucket or not change in media library.

If i remove all records with `meta_key = 'amazonS3_info'` in the `wp_postmeta` table and force regenerate images the plugin updates bucket url in contents. The problem is that my files are in AWS S3 and not more in host, 200GB +. The host not have storage for the size of media library if migrate from AWS.

How update references via database or script to new bucket?

![image](https://user-images.githubusercontent.com/3449932/61016850-85027300-a367-11e9-841d-f2847ef27b72.png)

**Comment by ianmjones** [comment]
@tiagoboeing When manually updating those "amazonS3_info" records you have to be very very careful that you properly set the length indicator of any altered value entry in this serialized data, otherwise PHP will refuse to unserialize the data.

If you remove those "amazonS3_info" records and try and force a re-offload via thumbnail regeneration then WP Offload Media will naturally not be able to offload the files if you've removed the local files.

This is why WP Offload Media has a "Copy files to new bucket" tool.

https://deliciousbrains.com/wp-offload-media/doc/how-to-copy-media-between-buckets/
