### ISSUE TITLE
Error fetching buckets — SyntaxError: Unexpected token S in JSON at position 0

### ISSUE THREAD

**Issue by kanipriyanka** [deliciousbrains/wp-amazon-s3-and-cloudfront#506]
Error fetching buckets — SyntaxError: Unexpected token S in JSON at position 0

Hi,
I am unable to fetch bucket from my aws s3 to wordpress.
Given Access key and Secret access key correct, but not fetching S3 bucket.
We are following this doc link to configure s3 and word press : https://www.codeinwp.com/blog/wordpress-s3-guide/

And we define below steps also  in wp-config.php
 define( 'WP_DEBUG', false );
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

**Comment by ianmjones** [comment]
Take out that first `define( 'WP_DEBUG', false );`, otherwise I suspect you're getting errors related to trying to re-define a constant.

If that doesn't fix things up for you, check you browser for what's coming back from the admin-ajax.php call, chances are you've got some non-JSON stuff in there.

Otherwise, please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
