### ISSUE TITLE
Help: Cname does not allow / , filepath workaround is not working

### ISSUE THREAD

**Issue by afridley** [deliciousbrains/wp-amazon-s3-and-cloudfront#507]
I'm trying to upload to an existing bucket

When I enter the Cname used previously on another site is https://www.example.com/example-uploads

However, I cannot enter a / in offload media

I have tried using a file path. Which looks right on the WordPress side and can give me https://www.example.com/example-uploads

However, in the bucket, it creates the folder example uploads. So the path https://www.example.com/example-uploads/image.jpg does not actually work as it should be https://www.example.com/example-uploads/example-uploads/image.jpg because of the created folder.

Is there a way to bypass the invalid character warning of the admin panel cname or could you add the abilities to add / to cnames

**Comment by ianmjones** [comment]
I think there's some confusion about CNAMEs and paths here.

A CNAME can not have a path in it, it is an alias for another domain, domains do not have paths.

WP Offload Media has a "Path" setting that allows you to change the base path that is used for offloading media in the bucket to. Normally the same base path as used as the WordPress media library does, e.g. "wp-content/uploads/", optionally with the "Year/Month" setting turned on so that the path ends up as "wp-content/uploads/2019/07/" before the optional object version element and actual file name.

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
