### ISSUE TITLE
WPML and S3 copy locally

### ISSUE THREAD

**Issue by JulienHe** [deliciousbrains/wp-amazon-s3-and-cloudfront#508]
Hello,

I sent a ticket to resolve an issue that I have with WPML and WP amazon s3.
The issue is actually know from what I check online and wpml team redirect me to you.

This is the original post that I sent https://wpml.org/forums/topic/assets-are-copied-to-local-machine-instead-of-s3-when-translated/ and then they told me that my issue was related to this one : https://wpml.org/forums/topic/offload-s3-integration-not-working/page/3/#post-2576661

Do you have any idea of where I should check??

Thanks!

**Comment by ianmjones** [comment]
@JulienHe WP Offload Media Lite does not support WPML's duplicate media process, WP Offload Media does.

We strongly recommend using "Media Translation" in WPML rather than Duplicate Media, this way you only need to translate caption/alternate text etc for an image, the exact same offloaded Media Library item is used. If an image needs to be different on a translated post because the original has text or symbols in it that need to be different in the secondary language, then Media Translation allows you to **add** another Media Library item to be used for that language (which WP Offload Media will offload and remove from local if that setting is turned on).

WP Offload Media has built in integration for when using WPML's "Duplicate Media" functionality, and will recognise when WPML creates a new duplicate Media Library item that references the original's path, so as to not re-offload to S3. It does however have to count the new Media Library item as offloaded, because it is a separate Media Library item record.

If for some reason you can't use WPML's Media Translation and must use WPML's Duplicate Media, then you will need WP Offload Media, not WP Offload Media Lite.
