### ISSUE TITLE
Autoload fatal errors with Google Cloud Storage

### ISSUE THREAD

**Issue by jawngee** [deliciousbrains/wp-amazon-s3-and-cloudfront#510]
Vanilla bedrock installation.

Installed the plugin via Composer and from wp.org.

I can get to the setup screen where I specify a bucket, but after I click "Save Bucket Setting" I get this error:

`Fatal error: Uncaught Error: Call to undefined function DeliciousBrains\WP_Offload_Media\Gcp\GuzzleHttp\choose_handler() in /srv/www/mediacloud.test/current/web/app/plugins/wp-amazon-s3-and-cloudfront/vendor/Gcp/guzzlehttp/guzzle/src/HandlerStack.php on line 37`

The only way I got past that was including the `/vendor/Gcp/guzzlehttp/guzzle/src/functions.php` in your plugin main.

After that I get:

`Fatal error: Uncaught Error: Call to undefined function DeliciousBrains\WP_Offload_Media\Gcp\GuzzleHttp\Psr7\uri_for() in /srv/www/mediacloud.test/current/web/app/plugins/wp-amazon-s3-and-cloudfront/vendor/Gcp/google/cloud-core/src/UriTrait.php on line 57`

I do a similar thing and include `/vendor/Gcp/guzzlehttp/psr7/src/functions.php` in your plugin main.  

And then I get:

`Fatal error: Uncaught Error: Call to undefined function DeliciousBrains\WP_Offload_Media\Gcp\GuzzleHttp\Promise\promise_for() in /srv/www/mediacloud.test/current/web/app/plugins/wp-amazon-s3-and-cloudfront/vendor/Gcp/guzzlehttp/guzzle/src/Client.php on line 230`

Which I then fix by including `'/vendor/Gcp/guzzlehttp/promises/src/functions.php` in your plugin main.

Not sure if this is caused by bedrock (I can't imagine how) and I haven't tested it in a plain jane setup because honestly I'm just testing compatibility with Media Cloud.

Steps to reproduce:

1. Install wordpress via bedrock/trellis
2. Install the plugin
3. Configure GCS creds either way (via file or via database) 
4. Enter in your bucket and click save

System Info:

- Ubuntu 18
- Nginx
- PHP 7.3 via PHP-FPM
- WordPress 5.2
- No other plugins installed or activated

**Comment by ianmjones** [comment]
Very likely down to another plugin also using the GuzzleHttp library but not scoping it within their namespace, and using a different version.

We scope our use of embedded libraries such as the AWS and GCP SDKs and their dependents, but if another plugin loads an unguarded and incompatible version first then there could be problems.

https://deliciousbrains.com/wp-offload-s3-1-6-released/#how

https://deliciousbrains.com/php-scoper-namespace-composer-depencies/

Not sure how we could get around this at the moment, other than asking you to contact the other plugin author to fix their scoping.

**Comment by jawngee** [comment]
It’s the only plugin installed and activated.

-- 

jon gilkison
principal, interfacelab
https://linkedin.com/in/jongilkison <https://linkedin.com/in/jongilkison>
https://github.com/jawngee <https://linkedin.com/in/jongilkison>
http://interfacelab.io/ <http://interfacelab.io/>

**Comment by jawngee** [comment]
It seems like your autoloader isn't including the namespaced functions.

**Comment by ianmjones** [comment]
Does Bedrock/Trellis include GuzzleHttp in its stack?

**Comment by jawngee** [comment]
No, and it wouldn't matter.  The error is that it can't find the function in *your* namespace:  DeliciousBrains\WP_Offload_Media\Gcp\GuzzleHttp\choose_handler()

Another library including GuzzleHttp would only be an issue if the namespace of what they were including matched up with yours.

**Comment by ianmjones** [comment]
@jawngee We've seen customers that use composer to deploy various features with their WordPress install have a version of GuzzleHttp autoloaded without a namespace as a dependency of their custom code or included library.

Please double check that your vendor directory does not include Guzzle somewhere.

We're going to try and find a way of better protecting WP Offload Media from versions of libraries that are included in the global namespace or otherwise stop its namespaced version from being loaded. If you have any ideas on that, we're all ears!

**Comment by ianmjones** [comment]
Umm, so a little birdie just clued me into the problem, and we'll hopefully have a fix for the next version of WP Offload Media, possibly 2.3.1, if not, then 2.4.

It's related to how composer tries to be efficient in how it autoloads class files by using a hash lookup based on file names. Unfortunately it does not support multiple versions of the same relative file name offset by namespace etc, and therefore two completely different versions of the same class with different content and namespace receive the same hash key.

This means once `GuzzleHttp.php` is loaded as a dependency from one path, it'll not bother loading our namespaced version from a completely different path because the hash key is the same. It assumes they're the same file.

We have a potential fix for this as it's been an issue other projects have had to work around too.

https://github.com/owncloud/files_primary_s3/pull/237/files#diff-89e7fc97925a92c2521656947a720895

**Comment by ianmjones** [comment]
WP Offload Media (Lite) 2.3.2 was released last week with a fix for this.
