### ISSUE TITLE
STS Libraries Omitted from vendored AWS Client

### ISSUE THREAD

**Issue by pcfens** [deliciousbrains/wp-amazon-s3-and-cloudfront#551]
Thanks for updating the AWS SDK vendored as part of this module in #536.

To use IAM roles in some situations the STS library is required too. In my case I'm using [EKS IAM role for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), but as I read more about STS things it sounds like it's required for a lot of other IAM role things.

The specific file that's missing is  `amazon-s3-and-cloudfront/vendor/Aws3/Aws/Sts/StsClient.php`, though I expect it includes more.

If it helps, I'm happy to test a future version before it's tagged and released.

**Comment by ianmjones** [comment]
@pcfens Can you give is details of the actual errors you see?

**Comment by pcfens** [comment]
The error in the PHP log is
`PHP Fatal error:  require(): Failed opening required '/var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/Sts/StsClient.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/aws-autoloader.php on line 6, referer: https://sites-test.wm.edu/wp-admin/network/`

**Comment by runningman84** [comment]
I have the same error.

**Comment by runningman84** [comment]
Maybe it make sense to outline the problem here... users of k8s would either use kube2iam or oidc to provide iam credentials to the plugin.

In the past the kube2iam system worked just fine because it emulates a aws metadata service which provides the corresponding credentials. The update to a newer AWS sdk also provided support for the oidc method:
https://aws.amazon.com/de/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

The newer authorization based on oidc has priority over the old system. Therefore the SDK uses the stsclient to check if this auth is used.

This means the latest plugin version of wp-amazon-s3-and-cloudfront (which includes a new AWS SDK) does neither work with the old kube2iam concept nor the new oidc system.

I guess it would even break in a non container environment using normal ec2 instances.

**Comment by ianmjones** [comment]
@runningman84 Thanks for the extra info, very helpful.

> I guess it would even break in a non container environment using normal ec2 instances.

We've not seen that in support, so hopefully that's not the case.

**Comment by ianmjones** [comment]
Sts and its dependencies were added to an updated AWS PHP SDK embedded in WP Offload Media (Lite) 2.4.2.
