### ISSUE TITLE
Not able to upload file larger than 160MB

### ISSUE THREAD

**Issue by info2mj** [deliciousbrains/wp-amazon-s3-and-cloudfront#584]
I was trying to upload video mp4 file, size of 172mb, but got server error, as s3 doesn't allow to upload file larger than 160MB.
Do we have solution for this?

**Comment by ianmjones** [comment]
S3 allows 5Tb sized objects, but WP Offload Media's method of pushing to the bucket is limited to 4Gb.

What you're hitting is a limit on your server, not S3.

Best way around this at the moment is to add the mp4 to the bucket manually, and then use WP Offload Media's "Add Metadata" tool to link up a Media Library item with the object.

https://deliciousbrains.com/wp-offload-media/doc/add-metadata-tool/

However, you will need to "fake" the Media Library item some how as WP Offload Media currently does not (yet) have a tool for importing objects as new Media Library items.

We're also hoping to eventually add a "direct offload" feature to WP Offload Media so that files do not need to land on the server before being offloaded to the bucket.
