### ISSUE TITLE
Bug: SVGs not supported

### ISSUE THREAD

**Issue by simplenotezy** [deliciousbrains/wp-amazon-s3-and-cloudfront#591]
SVGs are not being uploaded to to Google Cloud Storage Bucket.

I have tried adding this code:

    function allow_svg_mime($mimes) {
        $mimes['svg'] = 'image/svg+xml';
        return $mimes;
    }

    add_filter('upload_mimes', __NAMESPACE__ . '\\allow_svg_mime');
    add_filter('as3cf_allowed_mime_types', __NAMESPACE__ . '\\allow_svg_mime');

But it doesn't seem to work.

Also prior to adding the filter, the file is actually uploaded, but if you go to the bucket link, it will complain:

![image](https://user-images.githubusercontent.com/3786627/143769481-4b97a3d1-e1c9-4666-a02b-4b5db3499c6d.png)

Related issues:
- https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/513

**Comment by simplenotezy** [comment]
`as3cf_allowed_mime_types` is deprecated. The following line works:

    add_filter( 'as3cf_gzip_mime_types', function( $mime_types, $media_library ) {
        unset( $mime_types['svg'] );

        return $mime_types;
    }, 10, 2 );

**Comment by ianmjones** [comment]
> `as3cf_allowed_mime_types` is deprecated. The following line works:
> 
> ```
> add_filter( 'as3cf_gzip_mime_types', function( $mime_types, $media_library ) {
>     unset( $mime_types['svg'] );
> 
>     return $mime_types;
> }, 10, 2 );
> ```

`as3cf_allowed_mime_types` is definitely **not** deprecated! :smile: 

As your fix was to stop the gzipping of SVGs, I think the issue is that whatever you used to allow uploads of SVGs didn't properly add SVG's mime type so that WordPress Core could supply the correct metadata to some later processes.

Ideally you'd use something like the [SVG Support](https://wordpress.org/plugins/svg-support/) plugin to properly enable SVG files, and then our `as3cf_allowed_mime_types` filter isn't needed either.
