### ISSUE TITLE
Feature Request: Ability to hide Browse existing buckets and Create new bucket options

### ISSUE THREAD

**Issue by rodrigo-arias** [deliciousbrains/wp-amazon-s3-and-cloudfront#606]
**Is your feature request related to a problem? Please describe.**
The plugin requires privileges for `ListAllMyBuckets` and `GetBucketLocation`. AWS does not allow you to create a policy that limits these actions to specific buckets. Ref.: https://stackoverflow.com/questions/6615168/is-there-an-s3-policy-for-limiting-access-to-only-see-access-one-bucket
Hiding the _Browse existing buckets_ and _Create new bucket_ options will prevent a specific client from viewing another client's list of buckets.

**Describe the solution you'd like**
Add a filter to remove the options https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/8f641c0523c45c324a4efaa227f99f52b883d619/view/bucket-select.php#L105

**Describe alternatives you've considered**
Maybe it's possible to require fewer permissions or filter the list of buckets to only show some?

**Additional context**
![CleanShot 2022-04-26 at 16 35 03](https://user-images.githubusercontent.com/11416255/165379731-41e8f149-d366-4841-b324-536fc0b3a308.png)

Great job with this plugin, if the feature makes sense I'm open to submit a pull request.

**Comment by ianmjones** [comment]
Thanks for the feature request @rodrigo-arias.

Have you considered using the `AS3CF_SETTINGS` define to set the `provider`, `region` and `bucket` so that they can not be changed?

https://deliciousbrains.com/wp-offload-media/doc/settings-constants/

When you define the bucket those "Browse existing buckets" and "Create new bucket" links will go away, and the bucket is readonly.

![2022-04-27-11-17-00_1391x672_scrot](https://user-images.githubusercontent.com/4710/165496808-a0245f6f-7bc7-4cc5-a6cc-8bae406265ac.png)

You can also set `access-key-id` and `secret-access-key` to lock them to a particular IAM User.


> Hiding the Browse existing buckets and Create new bucket options will prevent a specific client from viewing another client's list of buckets.

It sounds like you're using the same IAM User for multiple client sites?

That's not recommended, for obvious security reasons.

More so, we would recommend that the client has their own AWS account where the S3 bucket is created and use their own IAM User etc. This gives the client ownership of their assets should there be a parting of ways.

> if the feature makes sense I'm open to submit a pull request

Thanks, but we can't accept pull requests to this mirror repo.

**Comment by rodrigo-arias** [comment]
@ianmjones thanks for your quick response, that's a good suggestion. I hadn't noticed that setting those variables as constants disables the admin options.

I agree with you that having an AWS account per client is perhaps the ideal scenario, but it is not applicable to all types of clients.

My idea was to have one AWS account, one IAM User per client, and individual bucket access policies per IAM User, but since the latter is not possible, preventing other buckets from being listed with your suggestion seems to be enough.

I'm closing this issue, thanks again.
