### ISSUE TITLE
Bug: tiff images are not offloading to S3 in WordPress 6+

### ISSUE THREAD

**Issue by jeysaravana** [deliciousbrains/wp-amazon-s3-and-cloudfront#616]
**Describe the bug**
After WordPress 6.0 update, tiff files are not offloading to S3. I found the root cause of this issue as WordPress introduced the new meta `filesize` data `wp_update_attachment_metadata` hook ref: https://core.trac.wordpress.org/changeset/52837
this is failing the condition here https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/integrations/media-library.php#L130
Upload functionality of WordPress is working fine. it put the file in the Server but offload to S3 is not working. that's why I created the issue here.

Technically tiff is an image but WordPress doesn't create any sizes for this. because of that it is passing this condition and breaking the functionality.
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/integrations/media-library.php#L142-L152

**To Reproduce**
1. Install Offload media plugin
2. Update wordpress to 6.1.1
3. Upload any tiff image
4. see the URL

**Expected behavior**
TIFF file should be offloaded to S3

**Comment by ianmjones** [comment]
Hey @jeysaravana,

Thanks for the detailed bug report.

Unfortunately this looks to be more of a bug with WordPress than WP Offload Media, as the WP core `wp_get_missing_image_subsizes( $post_id )` function shouldn't be bailing early and returning the default array of thumbnail sizes. Ideally it should know it can't handle TIFF images and return an empty array as no thumbnails are expected or therefore missing.

As WP Offload Media is told the post is an image attachment, it has expected thumbnails, and all thumbnails are currently missing, it will wait until at least one thumbnail has been created to ensure it is safe to start offloading.

An ideal workaround would be to use a plugin that can generate the thumbnails for TIFF images (I have no recommendation for that).

Otherwise, to ensure WP Offload Media doesn't indefinitely wait on thumbnails that aren't going to be generated, try adding something like this to your child theme's `functions.php` file:

```php
function filter_intermediate_image_sizes_advanced( $new_sizes, $data, $post_id ) {
	$post = get_post( $post_id );
	if ( ! $post ) {
		return $new_sizes;
	}

	$file = get_attached_file( $post->ID );
	if ( ! $file ) {
		return $new_sizes;
	}

	if ( ! empty( $post->post_mime_type ) && 'image/tiff' === $post->post_mime_type ) {
		return array();
	}

	return $new_sizes;
}
add_filter( 'intermediate_image_sizes_advanced', 'filter_intermediate_image_sizes_advanced', 10, 3 );
```
