### ISSUE TITLE
Feature Request: Allow advanced users to re-use the same domain for distribution

### ISSUE THREAD

**Issue by dealer-solutions-gene** [deliciousbrains/wp-amazon-s3-and-cloudfront#645]
**Is your feature request related to a problem? Please describe.**
I'm building a cloud-front distribution where NextJS is the `/` default behavior, `/admin` is for WordPress, and `/assets` is for the S3 bucket, There is validation within the AS3CF admin that prohibits the use of the same domain as the website domain with the following code:

	if ( $this->domain === parse_url( network_home_url(), PHP_URL_HOST ) ) {
		throw new InvalidArgumentException(
			sprintf(
				__( '<code>%s</code> must not be the same as the site domain. Use a subdomain instead.', 'amazon-s3-and-cloudfront' ),
				$this->domain
			)
		);
	}

**Describe the solution you'd like**
I'd like to see if a simple `AS3CF_*` constant could be defined to skip this domain validation.

**Describe alternatives you've considered**
The alternative is of course to make a sub domain, or remove this line from the plugin every time I update.

**Additional context**
![image](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/assets/50188785/5bb6f8ce-31ad-408e-a566-8dc00deec92e)

With thanks

**Comment by ianmjones** [comment]
Assuming you're using CloudFront infront of the entire site, and as long as your media is being offloaded to the same relative path it has locally, e.g. `wp-content/YYYY/MM/example.png`, and not using Object Versioning, then you can turn off the "Deliver Offloaded Media" setting.

In that scenario WP Offload Media will carry on offloading media to the bucket where the CloudFront distribution will pick it up from, but WP Offload Media will not rewrite any URLs as they are effectively local URLs.

Otherwise, if any path URL rewriting is needed, WP Offload Media needs to know whether a URL about to be displayed to a site visitor is a local URL that needs to be rewritten to a remote one, and that can only be accomplished by using a different domain for the remote URL.

The same goes for when edited content is being saved, WP Offload Media needs to be able to recognise that a remote URL has been pasted into the content and should be rewritten to its associated local URL before the content is saved to the database.

Are your media URLs served via CloudFront the same as if served from the local server?

**Comment by ianmjones** [comment]
No response, closing.
